chore: update all packages to latest minor version, fix typecheck
wrap children in Table component with <></> to make the types match,
otherwise "yarn typecheck" gave e.g. error TS2322:
- Type 'ReactNode' is not assignable to type 'ReactI18NextChildren'.
  - Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not
    assignable to type 'ReactI18NextChildren'.
    - Property 'children' is missing in type 'ReactElement<any,
      string | JSXElementConstructor<any>>' but required in type
      'ReactPortal'.
      - {column.render('Header')}

refs PT-1884